class Patient {
  constructor(id, name, device, message) {
    this.id = id; // represents the id generated by the firestore
    this.name = name;
    this.device = device;
    this.message = message;
  }
}

module.exports = Patient;
