class User {
  constructor(id, profile, battery, device, temperature) {
    this.id = id; // represents the id generated by the firestore
    this.profile = profile;
    this.battery = battery;
    this.device = device;
    this.temperature = temperature;
  }
}

module.exports = User;
